### ISSUE TITLE
Adding to the FreeCAD Addon Manager

### ISSUE THREAD

**Issue by luzpaz** [erroronline1/estimateWB#5]
Let me know when you feel ready to add this workbench to the Addon Manager :wink:

**Comment by erroronline1** [comment]
wait, what?

**Comment by luzpaz** [comment]
https://wiki.freecad.org/AddonManager

**Comment by erroronline1** [comment]
being quite happy with the current state i'd feel ready. tried to make everything as tidy as possible. not sure if this tiny thing justifies a wiki article but would look into that if it is mandatory. you wouldn't mind doing the pull request and adding to .gitmodules by chance since you already have a fork?

**Comment by luzpaz** [comment]
@chennes any objection to add this to the addon manager?

**Comment by chennes** [comment]
No, seems fine to me. The path to the icon in package.xml is wrong, it should be a relative path (relative to package.xml, that is).

**Comment by erroronline1** [comment]
hopefully fixed by now. thx!

**Comment by luzpaz** [comment]
estimageWB is now available in the Addon Manager. Congrats!  
Please merge #6 and we're good to go!
